[workspace]

members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
mkpath-core = { path = "crates/mkpath-core" }
mkpath-grid = { path = "crates/mkpath-grid" }

[package]
name = "mkpath"
version = "0.1.0"
edition = "2021"

[dependencies]
mkpath-core = { workspace = true }
mkpath-grid = { workspace = true }

[dev-dependencies]
structopt = "0.3.26"
